dist: xenial

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install pipenv

install:
  - pipenv install --dev

script:
  - pipenv run lint
  - pipenv run test

after_success:
  - if [[ `python -c "import platform; print(platform.python_version())"` == 3.7* ]]; then
      pip install codecov;
      codecov;
    fi
